services:
  api:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    environment:
      - DATABASE_DSN=${DATABASE_DSN_LOCAL}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/go/src/app
      - go-mod-cache:/go/pkg/mod
    networks:
      - stack
    ports:
      - "${API_PORT}:${API_PORT}"

  postgres:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - stack
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      retries: 5

networks:
  stack:

volumes:
  db-data:
  go-mod-cache: