services:
  api:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_DSN}
    depends_on:
      - postgres
    networks:
      - stack
    ports:
      - "${API_PORT}:${API_PORT}"

  postgres:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - stack

networks:
  stack:

volumes:
  db-data: