run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - ineffassign
    - unused
    - goconst
    - goimports
    - gocognit
    - lll
    - staticcheck

linters-settings:
  goimports:
    local-prefixes: github.com/Aiszhio/Task

  gocognit:
    min-complexity: 55

  lll:
    line-length: 120