basePath: /
definitions:
  domain.Subscription:
    properties:
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  transport.ErrorResponse:
    properties:
      error:
        example: something went wrong
        type: string
    type: object
  transport.SubscriptionRequest:
    properties:
      end_date:
        type: string
      id:
        type: string
      price:
        minimum: 0
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  transport.SubscriptionSummaryRequest:
    properties:
      end_date:
        type: string
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    required:
    - end_date
    - service_name
    - start_date
    - user_id
    type: object
  transport.SuccessResponse:
    properties:
      message: {}
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST‑сервис для учёта онлайн‑подписок
  title: Subscriptions API
  version: "1.0"
paths:
  /subscriptions:
    post:
      consumes:
      - application/json
      description: Создаёт новую запись о подписке
      parameters:
      - description: JSON
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transport.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: Создать подписку
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: Получить подписку по ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      - description: JSON
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transport.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: Полное обновление подписки
      tags:
      - subscriptions
  /subscriptions/list:
    post:
      consumes:
      - application/json
      description: Возвращает суммарную стоимость подписок по фильтру
      parameters:
      - description: JSON
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transport.SubscriptionSummaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: total_cost
          schema:
            $ref: '#/definitions/transport.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.ErrorResponse'
      summary: Сумма подписок за период
      tags:
      - subscriptions
schemes:
- http
swagger: "2.0"
